sudo: false
language: c
cache:
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
env:
  global:
  - HACKAGE_USERNAME=parsonsmatt
  - secure: L8uvm71se42vYa2QY4vcNQmVLQNOE94x1vTSwS3DVWDoyPONQDmRU0egyuhHVzg8kTtrrd5ohM5sUve98zJNwmM1JE6bY5gq+s0jLf0o0x070vMC7a31DK+Pq9W4E8ndynTiZ7olcOCNcUNisDRhGAyAbPDd/Hy50+wyt5mXtl1TCVN5jazYnQ1w72xw2eJ4yaeuXdVGtXCux3Yk6bDFiUmSAfp9ByuLHMbHiUXpu7geiUw7nL39CaY1RvoUGP+H0QLvOAX84wEpycBAS0i5gnl4fFoILauSsVmAm9uvSjsS41HgkzzFtdFXOtjPgclXGpbBG1N+yXh6Lgjbbc3vz167wy1ObczoZvksTkIrMMawFFIVmjLsCPuSTTTIy0/y3M2VwZCJB+Iy/bqc8GizDak8pE+C5xkhj89SThiVpwMpBUEVLiQrPqNj3gHBVXvf40lYv53FzLPiv3UKpGVC2ti94Te61Kte3Haq9ogzh+x9PKiDSzgu3Hz89Cazhn1oX/gkVeMFbEA/XKEzhWCdgJ9uiSg4LUvHc2RC1iDBGVglsfB/+xSrYJCth12+bqyeYTfcNkG13ZP82Di9swM03fuhwEWZ4l+l4sRIG3YVb3we+a9MC7FD69qv3fsCWHKzihgwrrbiQLZ7VvVCCzEzE903Aa7+g0aXHQ8ulyNq/to=

matrix:
  include:
  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22 HAPPYVER=1.19.5 ALEXVER=3.1.7
    compiler: ": #GHC 7.10.3"
    addons:
      apt:
        packages:
        - cabal-install-1.22
        - ghc-7.10.3
        - happy-1.19.5
        - alex-3.1.7
        sources:
        - hvr-ghc
  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24 HAPPYVER=1.19.5 ALEXVER=3.1.7
    compiler: ": #GHC 8.0.1"
    addons:
      apt:
        packages:
        - cabal-install-1.24
        - ghc-8.0.1
        - happy-1.19.5
        - alex-3.1.7
        sources:
        - hvr-ghc
  - env: BUILD=cabal GHCVER=head  CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
    compiler: ": #GHC HEAD"
    addons:
      apt:
        packages:
        - cabal-install-head
        - ghc-head
        - happy-1.19.5
        - alex-3.1.7
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS=""
    compiler: ": #stack default"
    addons:
      apt:
        packages:
        - ghc-7.10.3
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver lts-3"
    compiler: ": #stack 7.10.2"
    addons:
      apt:
        packages:
        - ghc-7.10.2
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver lts-5"
    compiler: ": #stack 7.10.3"
    addons:
      apt:
        packages:
        - ghc-7.10.3
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver lts-6"
    compiler: ": #stack 7.10.3"
    addons:
      apt:
        packages:
        - ghc-7.10.3
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver lts-7"
    compiler: ": #stack 8.0.1"
    addons:
      apt:
        packages:
        - ghc-8.0.1
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver lts-8"
    compiler: ": #stack 8.0.2"
    addons:
      apt:
        packages:
        - ghc-8.0.2
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver lts-9"
    compiler: ": #stack 8.0.2"
    addons:
      apt:
        packages:
        - ghc-8.0.2
        sources:
        - hvr-ghc
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons:
      apt:
        packages:
        - libgmp
        - libgmp-dev
  - env: BUILD=stack ARGS=""
    compiler: ": #stack default osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver lts-3"
    compiler: ": #stack 7.10.2 osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver lts-5"
    compiler: ": #stack 7.10.3 osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver lts-7"
    compiler: ": #stack 8.0.1 osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver lts-8"
    compiler: ": #stack 8.0.1 osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver lts-9"
    compiler: ": #stack 8.0.2 osx"
    os: osx
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly osx"
    os: osx
  allow_failures:
  - env: BUILD=cabal GHCVER=head  CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
  - env: BUILD=stack ARGS="--resolver nightly"
before_install:
- unset CC
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

  # Use the more reliable S3 mirror of Hackage
  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config

  if [ "$CABALVER" != "1.16" ]
  then
    echo 'jobs: $ncpus' >> $HOME/.cabal/config
  fi
- PACKAGES=$(stack --install-ghc query locals | grep '^ *path' | sed 's@^ *path:@@')
install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  set -ex
  case "$BUILD" in
    stack)
      stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES
      ;;
  esac
  set +ex
script:
- |
  set -ex
  case "$BUILD" in
    stack)
      stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
      ;;
    cabal)
      cabal install --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES

      ORIGDIR=$(pwd)
      for dir in $PACKAGES
      do
        cd $dir
        cabal check || [ "$CABALVER" == "1.16" ]
        cabal sdist
        SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && \
          (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
        cd $ORIGDIR
      done
      ;;
  esac
  set +ex
- ./README.lhs
